// src/components/rich-editor/LexicalEditor/theme/codeHighlightTheme.ts
export const codeHighlightTheme = {
    code: "bg-gray-100 font-mono p-2 rounded my-2",
    codeHighlight: {
        atrule: 'text-blue-500',
        attr: 'text-blue-500',
        boolean: 'text-red-500',
        builtin: 'text-green-500',
        cdata: 'text-gray-500',
        char: 'text-green-500',
        class: 'text-blue-500',
        'class-name': 'text-blue-500',
        comment: 'text-gray-400 italic',
        constant: 'text-purple-500',
        deleted: 'text-red-500',
        doctype: 'text-gray-500',
        entity: 'text-yellow-500',
        function: 'text-green-500',
        important: 'text-red-500',
        inserted: 'text-green-500',
        keyword: 'text-purple-500',
        namespace: 'text-yellow-500',
        number: 'text-red-500',
        operator: 'text-purple-500',
        prolog: 'text-gray-500',
        property: 'text-blue-500',
        punctuation: 'text-gray-500',
        regex: 'text-yellow-500',
        selector: 'text-blue-500',
        string: 'text-green-500',
        symbol: 'text-purple-500',
        tag: 'text-blue-500',
        url: 'text-blue-500',
        variable: 'text-yellow-500',
    },
};
