// components/BackendTechTable.tsx
'use client';

import React from 'react';

interface TechItem {
    category: string;
    tech: string;
    description: string;
    alternatives: string;
    link: string;
    summary: string;
    tip: string;
    learningCurve: number;
    importance: number;
    required: boolean;
}

const techList: TechItem[] = [
    {
        category: '언어',
        tech: 'Java / TypeScript',
        description:
            'Spring 기반 주요 언어, 안정성과 생태계 우수 | 프론트/백엔드 모두에서 사용되는 언어로, TypeScript는 타입 안전성과 유지보수성이 뛰어남.',
        alternatives: 'Kotlin, Go',
        link: 'https://www.oracle.com/java/',
        summary: '백엔드·풀스택 핵심 언어',
        tip: 'Java 17 이상, TS 5.x 이상 사용 권장',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '프레임워크',
        tech: 'Spring Boot',
        description: 'Java 기반 마이크로서비스 및 REST API 개발 표준 프레임워크',
        alternatives: 'Micronaut, Quarkus',
        link: 'https://spring.io/projects/spring-boot',
        summary: 'Java 핵심 백엔드 프레임워크',
        tip: 'Spring Initializr로 빠르게 시작하기',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '프레임워크',
        tech: 'NestJS',
        description: 'Node.js 기반 MSA 백엔드 프레임워크로, TypeScript 완벽 지원',
        alternatives: 'Express, Fastify',
        link: 'https://docs.nestjs.com/',
        summary: 'Node MSA 통합 솔루션',
        tip: 'Module 단위 설계와 Dependency Injection 이해 필수',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: 'ORM',
        tech: 'JPA',
        description: 'Java Persistence API. 엔티티-DB 매핑용 표준 ORM',
        alternatives: 'MyBatis, jOOQ',
        link: 'https://spring.io/projects/spring-data-jpa',
        summary: 'Spring과 통합되는 ORM',
        tip: '복잡 쿼리 시 QueryDSL 병행 추천',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: 'ORM',
        tech: 'QueryDSL',
        description: '타입 안전한 JPQL 작성 지원 도구',
        alternatives: 'jOOQ, MyBatis',
        link: 'https://querydsl.com/',
        summary: '정적 쿼리 생성용 DSL',
        tip: 'Q 클래스 자동 생성 환경 구축 필요',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: 'ORM',
        tech: 'jOOQ',
        description: '타입 안전성과 가독성이 우수한 SQL DSL. 복잡한 쿼리 작성에 적합',
        alternatives: 'QueryDSL, MyBatis',
        link: 'https://www.jooq.org/',
        summary: 'SQL 중심 개발에 최적화됨',
        tip: 'MySQL/PostgreSQL 무료, Oracle 등 상용 DB는 유료 라이선스 필요',
        learningCurve: 4,
        importance: 4,
        required: true,
    },
    {
        category: 'ORM',
        tech: 'MyBatis',
        description: 'XML 기반 SQL 매퍼 프레임워크. 복잡한 쿼리에 강점',
        alternatives: 'JPA, jOOQ',
        link: 'https://mybatis.org/',
        summary: 'SQL 완전 제어 가능',
        tip: 'SQL 직접 작성하므로 생산성 저하 주의',
        learningCurve: 3,
        importance: 4,
        required: true,
    },
    {
        category: '데이터베이스',
        tech: 'PostgreSQL',
        description: '신뢰성과 기능이 풍부한 오픈소스 RDBMS. JSON, Full Text 검색 지원',
        alternatives: 'MySQL, MariaDB',
        link: 'https://www.postgresql.org/',
        summary: '엔터프라이즈 급 오픈소스 RDB',
        tip: 'CTE, Window 함수, JSON 연산 등 고급 기능 활용 가능',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '데이터베이스',
        tech: 'MySQL / MariaDB',
        description: '오픈소스 RDBMS로, LAMP 스택에서 많이 사용됨',
        alternatives: 'PostgreSQL',
        link: 'https://www.mysql.com/',
        summary: 'LAMP 환경 표준 RDB',
        tip: 'Replication, InnoDB 엔진 이해 필수',
        learningCurve: 2,
        importance: 4,
        required: false,
    },
    {
        category: '데이터베이스',
        tech: 'MongoDB',
        description: 'NoSQL 도큐먼트 DB. 비정형 데이터 저장에 최적화됨',
        alternatives: 'Couchbase, DynamoDB',
        link: 'https://www.mongodb.com/',
        summary: '문서 지향 NoSQL',
        tip: 'Schema-less이지만 모델링 신중하게 설계',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '데이터베이스',
        tech: 'ClickHouse',
        description: '초고속 컬럼형 OLAP 데이터베이스. 실시간 분석에 강력함',
        alternatives: 'Apache Druid, Apache Pinot',
        link: 'https://clickhouse.com/',
        summary: '실시간 대시보드·보고서 전용 DB',
        tip: '주로 통계 집계 용도로 사용',
        learningCurve: 4,
        importance: 4,
        required: true,
    },
    {
        category: '데이터베이스',
        tech: 'Redis',
        description: '인메모리 기반 고속 캐시/큐/세션 관리용 NoSQL DB',
        alternatives: 'Memcached',
        link: 'https://redis.io/',
        summary: '캐시 및 Pub/Sub 핵심',
        tip: 'Sorted Set, Streams 활용 추천',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '데이터베이스',
        tech: 'Elasticsearch',
        description: '분산형 검색 및 분석 엔진. 로그·텍스트 검색에 특화됨',
        alternatives: 'OpenSearch, Solr',
        link: 'https://www.elastic.co/elastic-stack',
        summary: '로그·텍스트 검색 엔진',
        tip: '인덱스 설계와 샤드 전략 중요',
        learningCurve: 4,
        importance: 3,
        required: false,
    },
    {
        category: '메시징 / 이벤트',
        tech: 'Kafka',
        description: '분산 스트리밍 플랫폼으로 대용량 이벤트 처리에 강력함',
        alternatives: 'RabbitMQ, Redis Streams',
        link: 'https://kafka.apache.org/',
        summary: '실시간 이벤트 스트리밍',
        tip: 'Topic/Partition 설계와 Consumer 그룹 관리 중요',
        learningCurve: 4,
        importance: 5,
        required: true,
    },
    {
        category: '메시징 / 이벤트',
        tech: 'Kafka Streams',
        description: 'Kafka 토픽을 실시간으로 처리·분석할 수 있는 라이브러리',
        alternatives: 'Apache Flink, Apache Spark Streaming',
        link: 'https://kafka.apache.org/documentation/streams/',
        summary: '실시간 스트림 처리',
        tip: 'State Store와 토폴로지 설계 이해 필수',
        learningCurve: 4,
        importance: 4,
        required: false,
    },
    {
        category: '메시징 / 이벤트',
        tech: 'Redis Streams',
        description: 'Redis 5.0부터 도입된 스트림 데이터 구조로 메시지 큐 대체 가능',
        alternatives: 'Kafka, RabbitMQ',
        link: 'https://redis.io/topics/streams-intro',
        summary: '경량 스트림 큐잉',
        tip: 'Consumer Group 패턴 이해 필요',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '메시징 / 이벤트',
        tech: 'RabbitMQ',
        description: 'AMQP 기반 메시지 브로커. 전통적으로 많이 사용됨',
        alternatives: 'Kafka, Redis Streams',
        link: 'https://www.rabbitmq.com/',
        summary: '메시지 큐 표준',
        tip: 'Exchange/Queue/Binding 구조 숙지',
        learningCurve: 2,
        importance: 3,
        required: false,
    },
    {
        category: '인증/보안',
        tech: 'JWT',
        description: 'JSON Web Token 기반 Stateless 인증 방식',
        alternatives: 'Session 기반 인증',
        link: 'https://jwt.io/introduction/',
        summary: '토큰 기반 인증',
        tip: 'Access/Refresh Token 분리 전략 권장',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '인증/보안',
        tech: 'OAuth2 / OpenID Connect',
        description: '소셜로그인·API 인증 표준 프로토콜',
        alternatives: 'SAML',
        link: 'https://oauth.net/2/',
        summary: 'API 인증 표준',
        tip: 'Grant Type별 흐름 이해 필수',
        learningCurve: 3,
        importance: 4,
        required: true,
    },
    {
        category: '인증/보안',
        tech: 'Keycloak',
        description: 'Open-source IAM 솔루션. SSO, RBAC 제공',
        alternatives: 'Auth0, AWS Cognito',
        link: 'https://www.keycloak.org/',
        summary: '사내·SaaS 인증 관리',
        tip: 'Realm, Client, Role 설정 중요',
        learningCurve: 4,
        importance: 5,
        required: true,
    },
    {
        category: '인증/보안',
        tech: 'Vault',
        description: 'Secret Management 및 데이터 보호 솔루션',
        alternatives: 'AWS Secrets Manager',
        link: 'https://www.vaultproject.io/',
        summary: '시크릿·키 관리',
        tip: 'ACL 정책·KV 엔진 설계 필수',
        learningCurve: 4,
        importance: 4,
        required: false,
    },
    {
        category: 'API Gateway',
        tech: 'Nginx',
        description: '고성능 Reverse Proxy / API Gateway. 로드밸런싱, SSL Termination 지원',
        alternatives: 'Kong, Envoy, Spring Cloud Gateway',
        link: 'https://nginx.org/',
        summary: '실전 운영 최적화',
        tip: '로드밸런싱과 캐시 병행 활용',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '통신',
        tech: 'gRPC',
        description: 'Protocol Buffers 기반 고성능 RPC 프레임워크',
        alternatives: 'REST, Thrift',
        link: 'https://grpc.io/docs/',
        summary: 'MSA 내부 통신 표준',
        tip: 'Proto 파일 버전 관리 중요',
        learningCurve: 4,
        importance: 5,
        required: true,
    },
    {
        category: '통신',
        tech: 'WebSocket',
        description: '양방향 실시간 통신 프로토콜',
        alternatives: 'SSE, Long Polling',
        link: 'https://developer.mozilla.org/ko/docs/Web/API/WebSockets_API',
        summary: '실시간 알림·채팅 필수',
        tip: 'Heartbeat, 재접속 로직 구현 필요',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '통신',
        tech: 'WebRTC',
        description: '브라우저 기반 P2P 미디어 스트리밍 프로토콜',
        alternatives: 'Agora, Twilio',
        link: 'https://webrtc.org/',
        summary: '실시간 음성/영상 통화',
        tip: 'ICE Candidate, STUN/TURN 서버 이해 필수',
        learningCurve: 4,
        importance: 4,
        required: true,
    },
    {
        category: '빌드/마이그레이션',
        tech: 'Flyway / Liquibase',
        description: '데이터베이스 버전 관리 및 마이그레이션 도구',
        alternatives: 'plain SQL, custom scripts',
        link: 'https://flywaydb.org/',
        summary: 'DB 스키마 버전 관리',
        tip: 'Repeatable Migration & Baseline 활용',
        learningCurve: 2,
        importance: 4,
        required: true,
    },
    {
        category: 'CI/CD',
        tech: 'Jenkins',
        description: '자동화 서버로 복잡한 배포 파이프라인 구축 가능',
        alternatives: 'GitHub Actions, GitLab CI, CircleCI',
        link: 'https://www.jenkins.io/',
        summary: '복잡한 배포 파이프라인 지원',
        tip: 'Pipeline as Code(Jenkinsfile)로 관리',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: 'CI/CD',
        tech: 'GitHub Actions',
        description: 'GitHub 상에서 직접 CI/CD 파이프라인 구축 가능',
        alternatives: 'Jenkins, GitLab CI',
        link: 'https://docs.github.com/actions',
        summary: '간편한 Git 연동 배포',
        tip: '컨테이너 기반 워크플로우 작성 추천',
        learningCurve: 2,
        importance: 4,
        required: true,
    },
    {
        category: '배포',
        tech: 'Docker',
        description: '컨테이너 기반 이식성 있는 배포 환경 구성 도구',
        alternatives: 'Podman, Buildah',
        link: 'https://docs.docker.com/',
        summary: '컨테이너 배포 표준',
        tip: 'Production 이미지 최소화(Docker Slim) 권장',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '배포',
        tech: 'Kubernetes',
        description: '컨테이너 오케스트레이션 플랫폼. 대규모 MSA 배포에 필수',
        alternatives: 'Docker Swarm, Nomad',
        link: 'https://kubernetes.io/',
        summary: 'MSA 운영 플랫폼',
        tip: 'Helm 차트, Namespace 전략 설계 필요',
        learningCurve: 4,
        importance: 5,
        required: true,
    },
    {
        category: '배포',
        tech: 'Helm',
        description: 'Kubernetes 배포를 위한 패키지 매니저',
        alternatives: 'Kustomize',
        link: 'https://helm.sh/',
        summary: 'K8s 배포 템플릿 관리',
        tip: 'Values 파일 관리 전략 고민 필수',
        learningCurve: 3,
        importance: 4,
        required: true,
    },
    {
        category: '배포',
        tech: 'ArgoCD',
        description: 'GitOps 방식으로 Kubernetes 배포 자동화',
        alternatives: 'FluxCD',
        link: 'https://argo-cd.readthedocs.io/',
        summary: 'Git 중심 배포 관리',
        tip: 'AppProject, SyncPolicy 설정 필요',
        learningCurve: 3,
        importance: 4,
        required: false,
    },
    {
        category: '모니터링',
        tech: 'Prometheus',
        description: '시계열 기반 메트릭 수집 시스템',
        alternatives: 'Datadog, Zabbix',
        link: 'https://prometheus.io/docs/',
        summary: '서버·애플리케이션 메트릭 수집',
        tip: 'Exporter 설정 및 Alertmanager 연동 필수',
        learningCurve: 3,
        importance: 5,
        required: true,
    },
    {
        category: '모니터링',
        tech: 'Grafana',
        description: 'Prometheus 등 메트릭 시각화 및 대시보드 도구',
        alternatives: 'Kibana, Superset',
        link: 'https://grafana.com/docs/',
        summary: '메트릭 대시보드 시각화',
        tip: 'Dashboard as Code(Terraform) 추천',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '로깅',
        tech: 'ELK Stack',
        description: 'Elasticsearch + Logstash + Kibana 통합 로깅 스텍',
        alternatives: 'Loki + Fluentd + Grafana',
        link: 'https://www.elastic.co/elastic-stack',
        summary: '분산 로그 수집 및 분석',
        tip: 'Index Template, ILM 정책 설계 중요',
        learningCurve: 4,
        importance: 4,
        required: false,
    },
    {
        category: '로깅',
        tech: 'Loki',
        description: 'Grafana Labs에서 만든 경량 로그 수집 시스템',
        alternatives: 'ELK Stack',
        link: 'https://grafana.com/oss/loki/',
        summary: '메트릭-로그 연동 최적화',
        tip: 'Promtail과 함께 사용',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: 'APM',
        tech: 'Sentry',
        description: '애플리케이션 오류 모니터링 및 실시간 알림 서비스',
        alternatives: 'New Relic, Datadog APM',
        link: 'https://sentry.io/',
        summary: '오류 추적·알림',
        tip: 'Release Tracking 설정 필수',
        learningCurve: 2,
        importance: 4,
        required: false,
    },
    {
        category: '테스트',
        tech: 'JUnit',
        description: 'Java 단위 테스트 표준 프레임워크',
        alternatives: 'TestNG, Spock',
        link: 'https://junit.org/junit5/',
        summary: '단위 테스트 필수',
        tip: 'Mocking 프레임워크 연동 고려',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '테스트',
        tech: 'Testcontainers',
        description: 'Docker 기반 통합 테스트 환경 구성 라이브러리. 실제 DB/서비스 환경 에뮬레이션 테스트 수행',
        alternatives: 'Embedded DB, LocalStack',
        link: 'https://www.testcontainers.org/',
        summary: '통합 테스트 자동화',
        tip: 'CI/CD와 연동하여 프로덕션과 유사한 테스트 환경 구축',
        learningCurve: 3,
        importance: 4,
        required: false,
    },
    {
        category: '테스트',
        tech: 'Mockito',
        description: 'Java 단위 테스트용 모킹 프레임워크',
        alternatives: 'JMockit, EasyMock',
        link: 'https://site.mockito.org/',
        summary: 'Mock 객체 생성',
        tip: 'BDDMockito 스타일 사용 권장',
        learningCurve: 2,
        importance: 4,
        required: false,
    },
    {
        category: '테스트',
        tech: 'SonarQube',
        description: '정적 코드 분석 및 코드 품질 관리 도구',
        alternatives: 'Checkmarx, ESLint(프론트)',
        link: 'https://www.sonarqube.org/',
        summary: '코드 품질 관리',
        tip: 'CFamily(Java) 플러그인 설정 필수',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '데이터 파이프라인',
        tech: 'Apache Airflow',
        description: 'DAG 기반 워크플로우 스케줄러 및 ETL 파이프라인 엔진',
        alternatives: 'Prefect, Luigi',
        link: 'https://airflow.apache.org/docs/',
        summary: '배치/ETL 스케줄링',
        tip: 'Operator 커스텀 자주 사용',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '데이터 파이프라인',
        tech: 'Debezium',
        description: 'CDC(Change Data Capture) 기반 실시간 데이터 스트리밍 도구',
        alternatives: 'Maxwell’s Daemon',
        link: 'https://debezium.io/docs/',
        summary: 'DB 변경 이벤트 스트리밍',
        tip: 'Connector 설정·Kafka 연동 필수',
        learningCurve: 4,
        importance: 3,
        required: false,
    },
    {
        category: '데이터 파이프라인',
        tech: 'Superset',
        description: 'Apache 기반 BI 대시보드 및 시각화 도구',
        alternatives: 'Metabase, Superset',
        link: 'https://superset.apache.org/',
        summary: '데이터 시각화·대시보드',
        tip: 'ClickHouse, PostgreSQL 등 DB 연결 설정 필요',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '인프라',
        tech: 'Consul',
        description: '서비스 디스커버리 및 설정 관리 도구',
        alternatives: 'Eureka, Zookeeper',
        link: 'https://www.consul.io/docs',
        summary: 'MSA 서비스 헬스체크·디스커버리',
        tip: 'Key/Value 스토어 활용 가능',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '인프라',
        tech: 'pgBouncer',
        description: 'PostgreSQL 커넥션 풀러로 연결 효율화',
        alternatives: 'Pgpool-II',
        link: 'https://www.pgbouncer.org/',
        summary: 'DB 커넥션 풀 관리',
        tip: '최대 클라이언트 설정 조정 필수',
        learningCurve: 2,
        importance: 3,
        required: false,
    },
    {
        category: '인프라',
        tech: 'MinIO / S3',
        description: '오브젝트 스토리지 서버 (S3 호환)',
        alternatives: 'Azure Blob, Google Cloud Storage',
        link: 'https://min.io/',
        summary: '파일·이미지 저장소',
        tip: 'IAM 정책·버전 관리 활용',
        learningCurve: 2,
        importance: 3,
        required: false,
    },
    {
        category: '인프라',
        tech: 'Mediasoup (WebRTC SFU)',
        description: '다자간 WebRTC 연결용 SFU 서버 라이브러리',
        alternatives: 'Janus, Jitsi',
        link: 'https://mediasoup.org/documentation/',
        summary: '다자간 음성/영상 통화 지원',
        tip: 'SFU 토폴로지 이해 필수',
        learningCurve: 4,
        importance: 3,
        required: false,
    },
    {
        category: '인프라',
        tech: 'Traefik',
        description: '동적 라우팅을 지원하는 클라우드 네이티브 Edge Router',
        alternatives: 'NGINX, Envoy',
        link: 'https://doc.traefik.io/traefik/',
        summary: '동적 서비스 디스커버리 및 라우팅',
        tip: 'Let's Encrypt 자동 TLS 셋업 가능',
    learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '캐시/세션',
        tech: 'Redis (Cache / Pub/Sub)',
        description: '인메모리 기반 고속 캐시 및 Pub/Sub 서비스',
        alternatives: 'Memcached',
        link: 'https://redis.io/',
        summary: '상태 캐싱·메시징',
        tip: 'TTL 정책 및 Eviction 전략 설정',
        learningCurve: 2,
        importance: 5,
        required: true,
    },
    {
        category: '문서화',
        tech: 'Swagger / OpenAPI',
        description: 'REST API 자동 문서화 및 테스트 도구',
        alternatives: 'Postman Doc, Redoc',
        link: 'https://swagger.io/specification/',
        summary: 'REST 스펙 문서화 최적화',
        tip: 'Swagger UI로 바로 테스트 가능',
        learningCurve: 1,
        importance: 5,
        required: true,
    },
    {
        category: '문서화',
        tech: 'GraphQL 문서화 도구',
        description: 'GraphQL 스키마 시각화 및 문서 자동화 도구 (예: Apollo Studio, GraphQL Voyager)',
        alternatives: 'Hasura, GraphQL Mesh',
        link: 'https://www.apollographql.com/docs/studio/explorer/',
        summary: 'GraphQL API 문서화',
        tip: '스키마 변경 시 문서 자동 갱신 필요',
        learningCurve: 2,
        importance: 4,
        required: true,
    },
    {
        category: '데스크톱',
        tech: 'Electron / Tauri',
        description: '웹 기술 기반 데스크톱 애플리케이션 제작 도구',
        alternatives: 'Neutralino, Flutter (desktop)',
        link: 'https://tauri.app/',
        summary: 'Electron은 무겁지만 기능 풍부, Tauri는 가볍고 보안·성능 장점',
        tip: 'Tauri 사용 시 Rust 빌드 구성 필요',
        learningCurve: 3,
        importance: 3,
        required: false,
    },
    {
        category: '기타',
        tech: 'MCP (Multi-Channel Panel) 도구',
        description: '콜센터 멀티 채널 UI 통합을 위한 대시보드·커스터마이징 도구',
        alternatives: '내부 개발 솔루션',
        link: '-',
        summary: '멀티 채널 제어 UI',
        tip: '고객 컨텍스트 동기화 로직 중요',
        learningCurve: 3,
        importance: 4,
        required: false,
    },
];

const BackendTechTable: React.FC = () => {
    return (
        <div className="w-full overflow-x-auto py-10">
            <table className="min-w-full border border-gray-300 text-sm">
                <thead className="bg-gray-100 text-gray-900">
                    <tr>
                        <th className="border px-4 py-2">분류</th>
                        <th className="border px-4 py-2">기술</th>
                        <th className="border px-4 py-2">설명</th>
                        <th className="border px-4 py-2">대안</th>
                        <th className="border px-4 py-2">공식 문서</th>
                        <th className="border px-4 py-2">요약</th>
                        <th className="border px-4 py-2">팀 내 팁</th>
                        <th className="border px-4 py-2">러닝 커브</th>
                        <th className="border px-4 py-2">중요도</th>
                        <th className="border px-4 py-2">필수 여부</th>
                    </tr>
                </thead>
                <tbody>
                    {techList.map((item, index) => (
                        <tr key={index} className="hover:bg-gray-50">
                            <td className="border px-4 py-2 whitespace-nowrap">{item.category}</td>
                            <td className="border px-4 py-2 font-medium text-gray-800">{item.tech}</td>
                            <td className="border px-4 py-2 text-gray-700">{item.description}</td>
                            <td className="border px-4 py-2 text-gray-600">{item.alternatives}</td>
                            <td className="border px-4 py-2">
                                <a
                                    href={item.link}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-blue-600 hover:underline"
                                >
                                    링크
                                </a>
                            </td>
                            <td className="border px-4 py-2 text-gray-700">{item.summary}</td>
                            <td className="border px-4 py-2 text-gray-700">{item.tip}</td>
                            <td className="border px-4 py-2 text-center">{item.learningCurve}</td>
                            <td className="border px-4 py-2 text-center">{item.importance}</td>
                            <td className="border px-4 py-2 text-center">
                                {item.required ? '✅ 필수' : '⚪ 비필수'}
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

export default BackendTechTable;
